name: Check labels

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check formatting of label files
      run: |-
        python tests/test_label_format.py
      env:
        ACCESS_TOKEN_GITHUB: ${{secrets.ACCESS_TOKEN_GITHUB}}
    - name: Update summary table for labels
      run: |-
        python docs/gen_summary_table.py
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "check-bot@example.com"
        git config --global user.name "check-bot"
        git add -A
        git commit -m "Updated!" || exit 0
        git push
